export const path = {
    HOME: '/*',
    LOGIN: 'login',
    DETAL_POST_TITLE_ID: 'chi-tiet/:title/:postId',
    CHO_THUE_CAN_HO: 'cho-thue-can-ho',
    CHO_THUE_MAT_BANG: 'cho-thue-mat-bang',
    CHO_THUE_PHONG_TRO: 'cho-thue-phong-tro',
    CHO_THUE_NHA: 'nha-cho-thue',
    SEARCH: 'tim-kiem',
    SYSTEM: '/he-thong/*',
    CREATE_POST: 'tao-moi-tin-dang',
    MANAGE_POST: 'quan-ly-bai-dang',
    EDIT_ACCOUNT: 'thong-tin-tai-khoan',
    DETAIL_ALL: 'chi-tiet/*',
};
